### PR TITLE
Added support for blacklisting domainlookups.. 

### PR DESCRIPTION
**Pull request by planeturban**
Added comma separated list 'block_domains' for domains to prefix with 'block_prefix' to be handled with fail2ban. Will also prefix invalid requests since those seems to be used by some scriptkiddies..

### CODE REVIEW

**Comment by iBaa** [comment]
Why do you have your PlexConnect DNS open to the public? It's supposed to only be triggered from your local aTV... there is next to no precaution against security threats!
Or do I interpret things wrong?

**Comment by planeturban** [comment]
No you don't. ;) I'm hosting one for friends and family.

It's a very locked down LXC container running PC, so it's of no use for sh-kiddies to hack into (one can't hardly use it, let alone access it outside lxc-connect). However, a high load of DNS queries seems to bring PC to a halt. And the best way to stop them seems to be by either blocking them or just not respond on the query.

**Comment by finkdiff** [comment]
We specifically don't support this configuration as only those users who really understand the risks and how to mitigate them should even consider exposing this to the internet, if you are doing so run your own locked down properly configured DNS server instead of the inbuilt PlexConnect one (we allow users to disable this and use their own for various reasons).

**Comment by lesander** [comment]
You shouldn't run the PlexConnect DNS server on any other place than your local area network..

**Comment by moodyblue** [comment]
Thanks for this pull request. I thought about this, and taking into account the comments from @iBaa and @finkdiff I've decided to reject it.

Users willing to implement this should create their own forks or use VPN's instead.

**Pull request closed without merging**
