### PR TITLE
Add Intercept Apple TV Icon with config

### PR DESCRIPTION
**Pull request by Fish2**
Also print if update is Intercept and if icon is Intercept
Need to add instructions to readme

### CODE REVIEW

**Comment by Fish2** [comment]
Instructions for use to be added to wiki then it ready

1. Disconnect you Internet from your modem/router This is critical or it will pull the icon from apple
2. On your ATV go to general and reset all settings
3. Now setup your DNS Settings on the ATV so it is using plex connects dns server
4. Reboot the ATV
5. Now the icon should show up and its all done you can now reconnect the internet

Icons you can intercept
'www.icloud.com': 'iMovieNewAuth',
'atv.hbogo.com': 'vega',
'atv.qello.com': 'qello',
'a248.e.akamai.net': 'hulu',
'appletv.vevo.com': 'com.vevo.appletv',
'apps.sho.com': 'com.smithsonian.appletv',
'appletv.watchdisneyjunior.go.com': 'com.disney.junior.appletv',
'appletv.watchdisneychannel.go.com': 'com.disney.channel.appletv',
'appletv.watchdisneyxd.go.com': 'com.disney.xd.appletv',
'ssl.weather.com': 'com.weather.appletv',
'secure.marketwatch.com': 'wsj',
'trailers.apple.com': 'movie-trailers',
'secure.showtimeanytime.com': 'com.showtime.appletv',
'vimeo.com': 'vimeo',
'd6mhwe3a8uvr5.cloudfront.net': 'skynews',
'video.pbs.org': 'com.pbs.appletv',
'neulion-a.akamaihd.net': 'com.mlssoccer.appletv',
'itunesconnect.apple.com': 'iTunesConnect',
'abcnews.go.com': 'com.abcnews.appletv',
'atvapp.willow.tv': 'com.willowtv.appletv',
'player.aetndigital.com': 'com.aenetworks.lifetime.appletv',
'www.crunchyroll.com': 'crunchyroll',
'watchabc.go.com': 'com.abc.appletv.v2',
'appletv.redbull.tv': 'com.redbulltv.appletv',
'neulion-a.akamaihd.net': 'NHL',
'appletv.cnbc.com': 'com.cnbc.appletv',
'appletv.now.nfl.com': 'com.nfl.now.appletv',
'secure.net.wwe.com': 'com.wwe.appletv.v2',
'api-global.netflix.com': 'netflix',
'player.aetndigital.com': 'com.aenetworks.appletv',
's.yimg.com': 'com.yahoo.screen.appletv',
'kids.pbs.org': 'com.pbskids.appletv.v2',
'kortv.com': 'com.wkntv.appletv',
'appletv.crackle.com': 'com.crackle.appletv.v2',
'd1d0j1u9ayd8uc.cloudfront.net': 'com.acc.appletv',
's.cdn.turner.com': 'nba',
'player.aetndigital.com': 'com.aenetworks.history.appletv',
'aptve.foxneodigital.com': 'com.foxnow.appletv',
'appletv.flickr.com': 'flickr',
'a248.e.akamai.net': 'carterville',
'securea.mlb.com': 'flagstaff',
'mobapi.bloomberg.com': 'com.bloomberg.appletv',
'aptve-fx.foxneodigital.com': 'com.fxnow.appletv',
'festival.itunes.apple.com': 'com.festival.appletv',
's.aolcdn.com': 'com.aolon.appletv'

**Comment by moodyblue** [comment]
Merged. Will update the Wiki. Thanks.

**Comment by moodyblue** [comment]
I think I've updated the wiki correctly, but you can check

https://github.com/iBaa/PlexConnect/wiki/Settings-for-advanced-use-and-troubleshooting

**Comment by moodyblue** [comment]
Problem: Applied your code, but instead of replacing the WSJ icon (the app I'm intercepting), it replaced Trailers instead.

**Comment by Fish2** [comment]
@moodyblue have you changed the config ?

**Comment by moodyblue** [comment]
My `Settings.cfg` file is
```
[PlexConnect]
enable_plexgdm = False
ip_pms = 10.100.10.100
port_pms = 32400
enable_dnsserver = True
port_dnsserver = 53
ip_dnsmaster = 10.100.10.1
prevent_atv_update = True
intercept_atv_icon = True
icon = wsj
enable_plexconnect_autodetect = True
ip_plexconnect = 0.0.0.0
hosttointercept = video-api-secure.wsj.com
port_webserver = 80
enable_webserver_ssl = True
port_ssl = 443
certfile = /share/PlexConnect/certificates/marketwatch.pem
allow_gzip_atv = False
allow_gzip_pmslocal = False
allow_gzip_pmsremote = True
loglevel = Normal
logpath = /share/PlexConnect/logs
```

**Comment by Fish2** [comment]
Thats very strange i will have to look in to it. it work perfectly for me on trailers.

**Comment by moodyblue** [comment]
With the above settings the "intercepted app" is WSJ, but the "intercepted icon" is trailers.

**Comment by moodyblue** [comment]
Sory, sorry, sorry.

Further tests revealed that no icon is loaded. I noticed that in your list the url for WSJ Video is different from mine (which is the actual one), could it be that there is a different name to put in `icon=` ?

**Comment by Fish2** [comment]
yer that might well be the case I'm not sure how to find out. might have to do a packet trace on a network and reset a ATV without any intercept on and see what they all link to. unless someone already knows if that up to date. one thing that might be worth testing is if using video-api-secure.wsj.com under the icon setting.

**Comment by Fish2** [comment]
Just had another look and using wsj should work as if i go to the page that the icon comes from i get http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/images/atv7/wsj@1080.png

**Comment by moodyblue** [comment]
wsj relates to the old url, that does not displays on my ATV anymore.
Unless we find the new name we have to abbandon WSJ as a source for Plex
icon.

2018-02-24 19:08 GMT+00:00 Fish2 <notifications@github.com>:

**Comment by moodyblue** [comment]
Found this name in the forum, will test later com.wsjlive.appletv.v2

2018-02-24 19:18 GMT+00:00 Hugo Castelo Branco <hugo.castelobranco@gmail.com

**Comment by moodyblue** [comment]
Thread https://forums.plex.tv/discussion/168847/new-wsj-plex-icon/p1

2018-02-24 19:32 GMT+00:00 Hugo Castelo Branco <hugo.castelobranco@gmail.com

**Comment by Fish2** [comment]
That might work the url is valid http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/images/atv7/com.wsjlive.appletv.v2@1080.png

**Pull request merged**
