### PR TITLE
Taglines

### PR DESCRIPTION
**Pull request by pudds**
Simple addition to the channel template here to allow channels to display a tag line on video clip objects.

### CODE REVIEW

**Comment by moodyblue** [comment]
Can you please elaborate on what this enhancement is supposed to do ? I can apply it to master if it makes sense for other users.

Thanks for the pull request.

**Comment by pudds** [comment]
Sorry, I honestly can't remember, I haven't been using PlexConnect for a while now (switched away from Apple TV).

If I recall correctly, it added some additional show info to one of the templates.

**Comment by Fish2** [comment]
been looking in to this and if you go to this page https://support.plex.tv/articles/201638786-plex-media-server-url-commands/ and use the find function the tagline seams to be a bit of a description of the content so a layer down from the title

**Comment by moodyblue** [comment]
Merged. Thanks.

**Pull request merged**
