### PR TITLE
Version check

### PR DESCRIPTION
**Pull request by rcgiz40**

### CODE REVIEW

**Comment by moodyblue** [comment]
What's the purpose of this request ?

**Comment by rcgiz40** [comment]
Mostly so I can get a code for TestFlight. 

Grant Zucker
ZConcepts
386-689-2993

**Comment by moodyblue** [comment]
Thanks for your reply. I'm trying to clean this repo. I will apply some pull requests and reject others. Your pull request was made one year ago, long before I had update access to the repo, and now has conflicts that I can't resolve myself, so I'm afraid I will have to reject it.

I didn't know what TestFlight is, so I searched google. Are you a developer ? Do you have some spare time to enhance PlexConnect ?

I don't mind accepting a new pull request for what you need, although I don't think that it will be used by others, provided that it does not break all other users. We can discuss further in Slack, if you want I can post an invitation here

**Comment by rcgiz40** [comment]
I’m trying to get into it. I’m just a novice at this point. But I’d be interested in trying to help. 

Grant Zucker
ZConcepts
386-689-2993

**Pull request closed without merging**
