### PR TITLE
Hd Trailers

### PR DESCRIPTION
**Pull request by cdoe**
I was curious why the youtube trailers linked from TheMovieDB always showed in SD.  After some digging, I found it was due to the itag being 18.  Based on an itag list [here](https://github.com/rg3/youtube-dl/issues/1687), couldn't we default to 1080p, 720p, and then SD? I'm not a serious Python dev, so I'm sure you guys can find a better way about this, but it's just an idea.

### CODE REVIEW

**Comment by akmal** [comment]
I just pulled the changes and it works well. I do like having 1080p trailers instead of the SD ones. Good change.

**Comment by iBaa** [comment]
Doesn't look like a big change, I guess we could aft it to the main stream.
One thing to keep in mind though: Now that PMS is providing trailers again, we were actually discussing to get rid of this PlexConnect owned feature - it doesn't make much sense any more, does it?

**Comment by akmal** [comment]
I haven't looked at the PMS trailers. Are they in HD? If not, then this still makes sense.

**Comment by RageInvader** [comment]
Please add this in its a simple quick addition at least until plex handle the trailers.

:)

**Comment by iBaa** [comment]
Question: What about the "Plex/PMS provided trailers"? Are they still limited to PlexPass users? I really don't see a point of putting work into that feature - other than removing it, that is. :-D

**Comment by akmal** [comment]
Most of the trailers provided by Plex are low rez.

**Comment by RageInvader** [comment]
I think Plex/PMS provided trailers must still be a PlexPass feature as, I don't see it anywhere in PlexConnect or the web browser...

I personally manually edit the single file overtime you bring out an update so I can get HD trailers, of films.

**Comment by moodyblue** [comment]
Trailers support should be consistent across plex clients. Therefore no need to have trailers implemented in PlexConnect.

**Pull request closed without merging**
