### PR TITLE
Change Client to tvOS to support newer aTV firmware.

### LINKED ISSUE #458: Dolby Digital not working on newer aTV firmware
I am getting PCM playback as of a couple months ago. There is a forum post on the fix here:

http://forums.plex.tv/discussion/comment/1283332/#Comment_1283332

I will make a PR, its a simple fix!

### PR DESCRIPTION
**Pull request by marr**
Fixes #458

### CODE REVIEW

**Comment by carlsteinhilber** [comment]
Why? When the Plex app runs on tvOS directly (ie. - you don't even NEED PlexConnect on newer aTV firmware). Leave PlexConnect as is for those of us who are still using it as intended; on aTV3's and earlier.On Jan 24, 2017 8:57 PM, David Marr <notifications@github.com> wrote:Fixes 458



You can view, comment on, or merge this pull request online at:
  https://github.com/iBaa/PlexConnect/pull/459

Commit Summary
Change Client to tvOS to support newer aTV firmware.

File Changes

    M
    PlexAPI.py
    (4)
  

Patch Links:
https://github.com/iBaa/PlexConnect/pull/459.patchhttps://github.com/iBaa/PlexConnect/pull/459.diff

**Comment by marr** [comment]
I am using atv v3, which afaik won't run Plex natively. This fixes the issue I linked for getting 5.1 back with newer firmware on the gen 3.

**Comment by dnisbet** [comment]
Yeah this fixes it for me, dolby digital now via ATV3 instead of just PCM.

**Comment by dnisbet** [comment]
Now breaking output on server 1.5.3.3580. No output for DTS soundtracks.

**Comment by dnisbet** [comment]
However, a modification of the tvOS profile changes the order back to AC3 over EAC3: http://forums.plex.tv/discussion/266508/no-more-dolby-digital-in-atv-option-in-pms-plexconnect-since-update-1-5-3-3580#latest

**Comment by moodyblue** [comment]
I have submitted another pull request that superseeds this one. The iOS profile continues to be used so that users with ATV4's plus ATV3's can enjoy the full capabilities of each platform, instead of limiting ATV4 to what is available on ATV2/3.

**Pull request merged**
