### PR TITLE
Use broadcast to do GDM, too.

### PR DESCRIPTION
**Pull request by bcse**
I have 2 Plex media servers in my LAN. After the changes in 399719c582e76e736a44e7111e28f46972cd0f59. I can only discover one of them.
I don't know exactly why. But previous version works for me. This PR is to use both multicast and broadcast for GDM and combine both results. It should have better compatibility with various network settings.

### CODE REVIEW

**Comment by bcse** [comment]
Also, I just found this: #7.

**Comment by iBaa** [comment]
Hi!
I remember that we somewhat jumped back and forth on that one... interesting idea to check both ways and trust the sum. :-D

**Comment by iBaa** [comment]
Couple of questions:
- You don't seem to make sure that we don't get a duplicate response from one PMS in the end - in case the PMS would answer to both requests, right? I am not sure is this has a risk of screwing up the g_PMS[] dictionary. It should just overwrite the first response, but I guess I need to understand that better.
- Is it possible to send both request messages using one and the same socket instance? Like just duplicating the "sendto" in line 160 with the <broadcast> address?
```
GDM.sendto(Msg_PlexGDM, (IP_PlexGDM, Port_PlexGDM))
GDM.sendto(Msg_PlexGDM, ('<broadcast>', Port_PlexGDM))
```
That way we might already get all responses combined (probably with duplicates as well), with only one time the 1sec timeout.
Any idea? I guess I have to do some testing...

**Comment by bcse** [comment]
* There are duplicate in returnData. We use returnData to create PMS_list, PMS_list is a dictionary that use PMS UUID as key, so it will eliminate the duplicates.
* I don't think you can do this since they have different sockopt:

```
GDM.setsockopt(socket.IPPROTO_IP, socket.IP_MULTICAST_TTL, struct.pack('b', 1))
GDM.setsockopt(socket.SOL_SOCKET, socket.SO_BROADCAST, 1)
```

**Comment by moodyblue** [comment]
I don't have ways to reproduce and test. PlexConnect finds several PMS's when logged to plx.tv, so probably not needed anymore.

Closing. I will reopen if needed.

**Pull request closed without merging**
