### PR TITLE
Adding GZip compression for XML and JS serving

### PR DESCRIPTION
**Pull request by LucianPx**
Helps with interface responsiveness, especially for users with large libraries and especially on high latency networks (also WiFi). Some served XML files are > 500 kB (GZipped only about 30 kB).

http://stackoverflow.com/questions/9622998/how-to-use-content-encoding-gzip-with-python-simplehttpserver

### CODE REVIEW

**Comment by roidy** [comment]
>For PMS/PlexConnect on low power NAS, it might be worth to disable that... I can't see a benefit if zipping if everything is internal to one box.

So is this optional? How do I turn it off? Did you do any benchmarks?

**Comment by iBaa** [comment]
Hu?
From the commit-comment:
>- allow PMS to gzip files requested by PlexConnect, if PMS/PlexConnect
hosts are different (have different IP addresses)

If PMS and PlexConnect is hosted on the same machine (so no network involved for communication), the committed code wouldn't ask for gzip. If this is not enough and we need another option to completely disable it, we have to add it... Optional a setting for the compression level, too.

**Comment by roidy** [comment]
>Hu?
 From the commit-comment:

Sure.... but that doesn't stop everything else from being zipped eg xml, js ...... I would bet that the decompression on the aTV's end isn't that fast either. Some of the xml's can be very large and this just add unneeded overhead zipping them up on lower powered devices.

>Nothing really scientific, much less with different machines.

This should really of been benchmarked before deciding that it suits every device :(

>But I found, that shutting down the debug logging has much more effect than that... :-D 

Exactly the reason I never run with debugging or logging turned on during everyday use.

Sure I can see the use for this for remote servers to cut down on internet traffic, but for local networks I'm guessing that a uncompressed data stream is faster than having to compress->transmit->uncompress.

**Comment by iBaa** [comment]
>This should really of been benchmarked before deciding that it suits every device :(

How in the world should I benchmark "every device"?

**Comment by roidy** [comment]
I never said benchmark "every device". Obviously you only need to benchmark a small selection of devices, and mainly just low powered ones.

What should have been done is a test app written that may be sends a set amount of data to the aTV and then sends a response back so the round trip could be timed using both standard and compressed data, this way you could ask people to test it and gather all the results to see if it really is a problem on low powered devices.

**Comment by iBaa** [comment]
Working on some benchmarks - and discovered one missing setup: aTV2 running PlexConnect. This would right now zip and zop all those XMLs as well - all in one box. :-(

**Comment by roidy** [comment]
Ok.... I'm not saying this is bad and I fully understand it for remote servers. I just don't see what we gain sending compressed data from PlexConnect to the aTV across a local network.

**Comment by iBaa** [comment]
> gain

Well, typically (at least nowadays) everything within CPU/main memory is a lot faster than access to external IO - like hard drives and stuff. I actually have heard about systems doing compression in RAM to save the swapping of virtual memory.

**Comment by roidy** [comment]
Sure on reasonably powerful hardware, but on low powered systems, especially arm based NAS boxes compression and decompression could take longer than just sending the data uncompressed. Read that article LucianPx posted:- https://devcentral.f5.com/articles/i-am-wondering-why-not-all-websites-enabling-this-great-feature-gzip especially the part I quoted in my response.

**Comment by iBaa** [comment]
Adding this to application.js/onAppEntry
```
  var time = new Date();
  var intHours = parseInt(time.getHours());
  var intMins = parseInt(time.getMinutes());
  var intSecs = parseInt(time.getSeconds());
  var totalTimeInSecs_A = ((intHours * 3600) + (intMins * 60) + intSecs);
  log("Benchmark");

    for (var i = 0; i < 100; i++)
    {
        var url = "{{URL(/SomeBigFile.xml)}}&PlexConnectUDID="+atv.device.udid
        var req = new XMLHttpRequest();
        req.open('GET', url, false);
        req.send();
        delete req;
    }
  var time = new Date();
  var intHours = parseInt(time.getHours());
  var intMins = parseInt(time.getMinutes());
  var intSecs = parseInt(time.getSeconds());
  var totalTimeInSecs_B = ((intHours * 3600) + (intMins * 60) + intSecs);
  log("Benchmark - request xml.raw - "+(totalTimeInSecs_B-totalTimeInSecs_A));
```
and modifying WebServer to actually just serve SomeBigFile.xml (bypassing XMLConverter) leads to a major aTV crash. :-(
Not sure how I can do some benchmarking there...

**Comment by roidy** [comment]
Umm... I would do the benchmark on the python side of things. Something like in application.js add:-

```
atv.onPageLoad = function(pageID) 
{
  var url = "{{URL(/)}}&PlexConnect=Benchmark" 
  var req = new XMLHttpRequest();
  req.open('GET', url, false);
  req.send();
}
```
 Then in Webserver.py grab the current time using time.time() or time.clock()  add a new command to XMLConverter.py for "Benchmark" that just grabs the time again and subtracts the original time you got from Webserver.py and print it. This way you can benchmark any page that is sent to the aTV.

Not sure weather this would work.... haven't really looked into it.

**Comment by cactus** [comment]
Why not just put nginx in front of plexconnect and have it do the compression for you?
That is what I do. Performs better than doing the compression in the web app anyway.

**Comment by roidy** [comment]
Because ideally for local network traffic we don't want to be doing any compression let alone adding another external dependence for it.

**Comment by carlsteinhilber** [comment]
Not to dis anyone... but doesn't the forum sound like a much more appropriate venue for this discussion? So we're not getting github notifications with each reply?

**Comment by cactus** [comment]
@carlsteinhilber Actually, in general most projects prefer to talk about features and bugs on the bug tracker (go figure). I just assumed that was the case with this project as well (could be wrong).

Github does allow you to mute some notifications -- on the right sidebar, under "notifications", there is an "unsubscribe" button. There is also an "unwatch" at the top of the project.

**Comment by carlsteinhilber** [comment]
@cactus I don't WANT to turn off notifications or unsubscribe, because they're useful to me to see when changes come through that I want to pull.

I guess I'm the only one that feels this way, so forget I said anything.

**Comment by iBaa** [comment]
Ok, first benchmarks are in.
From Mac to aTV via wired LAN (100MBit) or so, pulling a big XML (raw 2,7MB // zipped 122kB) 10 times in a row (aTV handles 10times just fine, crashes at higher numbers, see above), times in ms:
xml.raw - 1700
xml (pre-zipped) - 3200
xml (zipped online) - 3000
Honestly, I don't understand the later two. I guess I have to run it more often and do some statistics. Also want to try how WLAN affects things... but currently it really doesn't look like a gain, does it? :-D

**Comment by cactus** [comment]
@iBaa looking at c943e31254c021f8b831ddca8e9d555f94e95c79 it looks like you are using StringIO instead of cStringIO. You might gain some improvement by using cStringIO where available.

~~~
# Find the best implementation available on this platform
try:
    from cStringIO import StringIO
except:
    from StringIO import StringIO
~~~

**Comment by roidy** [comment]
>Ok, first benchmarks are in.

Could you send me the benchmark code. I'll try it on my low powered server. If that's on your Mac then I'm guessing the results will be even worse on lower powered hardware.

**Comment by iBaa** [comment]
added branch:
https://github.com/iBaa/PlexConnect/tree/Gzip_Benchmark
Just add a finished "AllMovies.xml" plus "AllMovies.xml.zip" in /assets/templates.
Interestingly today's numbers are completely off:
raw - 930
pre-zipped - 810
zipping online - 16870
With this, I don't think the analysis is valid... :-(

**Comment by roidy** [comment]
Could you also post the xml so we can try and keep the benchmarks the same.

Also what's the difference between AllMovies.xml and AllMovies.xml.raw ?

**Comment by roidy** [comment]
Ok, here's my results for a 1.1MB raw xml, 54kB zipped:-

i7@4.4Ghz
raw - 1713
pre-zipped - 8446
zipping online - 8333

AMD N40L Dual-Core@1.5Ghz
raw - 1925
pre-zipped - 6604
zipping online - 6547

Each test was preformed 5 times and the average taken. Seems to me any time you zip you increase the processing time by about 3-4 times regardless of cpu speed :(

**Comment by iBaa** [comment]
And here is the benchmark for accessing a remote PMS - half way through Europe.
XML RAW
size_download=3388920
Time in seconds: 17
XML ZIPPED
size_download=931711
Time in seconds: 6

Bottomline: I guess we will remove/disable the aTV gzip service code, but keep allowing PMS to use compressed communication when in a remote location. Is that reasonable?

**Comment by roidy** [comment]
Yep, that makes more sense.

**Pull request closed without merging**
