### PR TITLE
Support AC3 5.1 (DTS) and rotate photos

### PR DESCRIPTION
**Pull request by moodyblue**
Fixes included:
1) When video transcoding is required AC3 5.1 (DTS) audio is preserved
2) Photos are transcoded only when rotation is needed
3) Lossless audio (alac, aiff, wav) will DirectPlay always (no transcoding needed)

### CODE REVIEW

**Comment by dnisbet** [comment]
This seems to have broken something for me?

Traceback (most recent call last):
  File "./PlexConnect.py", line 19, in <module>
    import DNSServer, WebServer
  File "/home/dnisbet/PlexConnect/WebServer.py", line 29, in <module>
    import XMLConverter  # XML_PMS2aTV, XML_PlayVideo
  File "/home/dnisbet/PlexConnect/XMLConverter.py", line 1025
    orientation, leftover, dfltd = self.getKey(src, srcXML, 'Media/Part/orientation')
    ^
IndentationError: unexpected indent

**Comment by roidy** [comment]
Could you grab the new code and try it again please.

**Comment by dnisbet** [comment]
This is from a new clone.

**Comment by roidy** [comment]
Yes but I've just pushed new code so grab it again and try it.

**Comment by dnisbet** [comment]
Yep that new code has done the trick :)

**Comment by roidy** [comment]
Ok, thanks.

**Pull request merged**
