### PR TITLE
Custom DNS IP for docker

### PR DESCRIPTION
**Pull request by Fish2**
Change custom_dns_bind_ip from 0.0.0.0 to ip if required mainly for
docker use

### CODE REVIEW

**Comment by moodyblue** [comment]
Thanks for your pull request. PlexConnect already has these settings:
```
enable_plexconnect_autodetect = True
ip_plexconnect = 0.0.0.0
```
I think that you can use `enable_plexconnect_autodetect = False` and then code in `ip_plexconnect` the neede IP address, instead of creating yet another Setting parameter. What do you think ?

**Comment by Fish2** [comment]
They can't as it create more issues

**Comment by moodyblue** [comment]
Let's discuss in Slack. Bind to IP is an interesting capability, I wish PMS also had it... Maybe one day...

**Comment by moodyblue** [comment]
Can you pls resubmit your pull request ? I'm afraid that in its current state it has conflicts with base that I don't know how to solve.

**Comment by Fish2** [comment]
sorry had a couple of other things to do i have added a new pull request #527

**Pull request closed without merging**
