### PR TITLE
Add hostname to config fix issue #502

### PR DESCRIPTION
**Pull request by Fish2**
If you want to use a hostname for pms change hostname from none to the
hostname and plexconnect will ignore the ip in ip_pms and used host
name. Others can ignore this setting.

### CODE REVIEW

**Comment by moodyblue** [comment]
In principle I don't agree with this change but we can discuss, here or in Slack.

Remote PMS access is already possible through plex.tv and VPN, these are secure and proven methods, both of them supported by PlexConnect. Is there a need for an additional method ? Why ?

Furthermore it's my objective to grant some consistency with other Plex clients, where I'm not aware of such capability.

**Comment by Fish2** [comment]
plex.tv is not secure and you shouldn't have to use a VPN.

**Comment by moodyblue** [comment]
Regarding `plex.tv is not secure`, please read and comment this article https://blog.filippo.io/how-plex-is-doing-https-for-all-its-users/

**Comment by Fish2** [comment]
I don't mean not secure in that sense but using any external source is potentially not secure like in your case you prefer to use your own direct ip instead of GDM. So would other users but in some cases it's not posable to do with out allowing hostnames.

**Comment by moodyblue** [comment]
Can you pls review the `Hugo` branch ? I think that it provides the same function without requiring a new parameter in `Settings.cfg`

**Comment by Fish2** [comment]
could give it a try but it wont give a error if not configured right

**Comment by moodyblue** [comment]
I've made 3 tests (with `ip_pms` values)
1. With a correct IP - Ok
2. With a correct hostname - Resolves Ok
3. With incorrect hostname - Logs error message

**Comment by moodyblue** [comment]
Applied #526 instead. If this creates any issue let's solve it.

**Pull request closed without merging**
